{
    "version": "2",
    "volumes": {
        "postgres_data": {},
        "mysql_data": {}
    },
    "services": {
        "postgres": {
            "image": "postgres",
            "volumes": [
                "postgres_data:/var/lib/postgresql/data"
            ]
        },
        "mysql": {
            "image": "mysql",
            "environment": {
                "MYSQL_ALLOW_EMPTY_PASSWORD": "true"
            },
            "volumes": [
                "mysql_data:/var/lib/mysql"
            ]
        },
        "php-fpm": {
            "build": {
                "context": ".",
                "dockerfile": "Dockerfile-php-fpm"
            },
            "volumes": [
                "./:/var/www/html"
            ],
            "depends_on": [
                "postgres",
                "mysql"
            ]
        },
        "nginx": {
            "image": "nginx:alpine",
            "volumes": [
                "./:/var/www",
                "./nginx.php-fpm.conf:/etc/nginx/nginx.conf:ro"
            ],
            "ports": [
                "80:80"
            ],
            "depends_on": [
                "php-fpm"
            ]
        }
    }
}
